### ISSUE TITLE
[signup] clicking join leads to nothingness

### ISSUE THREAD

**Issue by lesleykg1** [theBoardlist/website#125]
Steps to reproduce:
1. Go to https://theboardlist.com/join
2. Click JOIN

Expected result:
sign up form displayed

Actual result:
no form shown

![screen shot 2016-07-07 at 10 42 25 am](https://cloud.githubusercontent.com/assets/16053877/16663093/b5f8f3e8-442f-11e6-8c7b-a62cd6a38389.png)

**Comment by jimmybyrum** [comment]
@lesleykg1 Just FYI this was because of some bad HTML in the `join-member-criteria` module.
https://theboardlist.com/admin/modules/join-member-criteria

Might be a good idea to have some history/undo capability on those modules.
