### ISSUE TITLE
Get some idea of current traffic/load

### ISSUE THREAD

**Issue by jimmybyrum** [theBoardlist/website#24]
### Current DB
684 Candidates
136 Endorsers
982 Endorsements (make sure these link correctly)

**Comment by RicardoSoftvision** [comment]
Skype chat is set for 10am Wednesday 12/2

**Comment by jimmybyrum** [comment]
Can we move this to 9:30 or 10:30? I have a daily standup from 10 - 10:30.

If we can't move it, I'll just join as soon as I can.

**Comment by RicardoSoftvision** [comment]
I'll check for the later time of 1030a

**Comment by jimmybyrum** [comment]
We talked with Anthony last week and he's going to try to get us some historical data, though we don't have a timeframe on when that will happen.
