### ISSUE TITLE
Password Reset Error

### ISSUE THREAD

**Issue by jimmybyrum** [theBoardlist/website#32]
from @lesleykg1 

steps: 1. on reset pw page, enter email address and click SEND EMAIL
2. click link in reset pw email
3. you get this error message

![image](https://cloud.githubusercontent.com/assets/440405/12205043/1330a960-b5ed-11e5-9c4b-4033630b2f77.png)

**Comment by jimmybyrum** [comment]
This is working ok for me. Each one of those links is a one-time only deal, so maybe you were seeing it because you went to the link a 2nd time? I will change it to expire after being used, or if the link is more than 24 hours old.

**Comment by jimmybyrum** [comment]
Sorry I was wrong about that- it removes the link after it's used. Can you just test again and if you're still seeing a problem, send me the email or url. Thanks!

**Comment by lesleykg1** [comment]
Still getting the link expired message. I'm trying to reset password for sarah@grossblatt.com

**Comment by jimmybyrum** [comment]
Can you send me the link you're using to reset the password?

**Comment by lesleykg1** [comment]
https://theboardlist.com/reset-password/b22ce4cafddbf68fdf5c280c6f2882ea__ATMAIL_ENCODED_EXISTING_URL_PGltZyBzcmM9Imh0dHA6Ly9jZG4ubWFpbHNjYW5uZXIuaW5mby8xeDFzcGFjZXIuZ2lmIiB3aWR0aD0iMSIgaGVpZ2h0PSIxIiBhbHQ9IldlYiBCdWcgZnJvbSBodHRwOi8vbWFuZHJpbGxhcHAuY29tL3RyYWNrL29wZW4ucGhwP3U9MzA3ODk0MTgmYW1wO2lkPWIyMzUwZTdmMmJlYzQwYWJiMDU1NTZhODhjMGIyYjFmIj4=_ATMAIL_ENCODED_EXISTING_URL__

**Comment by jimmybyrum** [comment]
What email client is this from? There's a ton of extra data being added to the end of the link

**Comment by lesleykg1** [comment]
sitemail.hostway.com (grossblatt.com hosting service)

**Comment by lesleykg1** [comment]
I wonder if other clients are doing something crazy like that?

**Comment by jimmybyrum** [comment]
I updated the email a smidge- can you try getting a new one sent and see if it works any better?

**Comment by lesleykg1** [comment]
Worked perfectly.
