### ISSUE TITLE
[edit profile] Q: is "company size" supposed to be a dropdown?

### ISSUE THREAD

**Issue by lesleykg1** [theBoardlist/website#39]

**Comment by jimmybyrum** [comment]
Sure. What should the options be?

**Comment by lesleykg1** [comment]
* 1-50 employees
* 51-100 employees
* 101-250 employees
* over 250 employees

I think you should be able to pick more than 1 size

**Comment by jimmybyrum** [comment]
I made both the company size and stages fields a checkbox list in edit mode. I think those are easiest to parse for short lists.

![image](https://cloud.githubusercontent.com/assets/440405/12215314/7b965508-b66b-11e5-8d31-47ecd03246aa.png)
