### ISSUE TITLE
[nominations count] more endorsements than nominations shouldn't happen

### ISSUE THREAD

**Issue by lesleykg1** [theBoardlist/website#55]
On this profile:
http://preview.theboardlist.com/candidate/gina-bianchini

She has 1 nomination and 3 endorsements. This shouldn't be possible. There should always either be the same # of nominations and endorsements, OR more nominations than endorsements.

**Comment by lesleykg1** [comment]
Could be that system is only showing 1 nomination for candidate, even when she has >1

**Comment by jimmybyrum** [comment]
@lesleykg1 I ran a script to try to fix this. It's looking a lot better, but let me know if anything else seems off.
