### ISSUE TITLE
[emails] turn on automated email notifications

### ISSUE THREAD

**Issue by lesleykg1** [theBoardlist/website#70]
- [x] when candidate is nominated
- [x] when endorser is approved
- [x] when searcher is approved

**Comment by jimmybyrum** [comment]
@lesleykg1 I have this ready to go for the Pending tab (though not uploaded yet). I wanted to check with you about the behavior on the Admin tab, which feels a bit more complicated.

On the Admin tab, you can toggle a type on and off. It'd be easy enough to say: when a user is toggled to be a candidate, send a welcome email. I guess I just want to avoid a situation where someone is toggled on/off/on and they receive the welcome email multiple times. Should I be worried about that, or should I just have it send emails from both the Pending and Approved tab.

**Comment by jimmybyrum** [comment]
Figured I might as well turn this on on the Pending tab, so it's live. Let me know what you think about the behavior on the Admin tab.

**Comment by lesleykg1** [comment]
If we can detect whether the user has already received the welcome email and suppress sending another, then I think it makes sense (and would be very helpful) to trigger from pending and admin.
