### ISSUE TITLE
Upload images

### ISSUE THREAD

**Issue by lesleykg1** [theBoardlist/website#86]
1. Stacy Brown-Philpot's headshot (we already have it uploaded, but I don't have the file location)
2. HP logo
![stacy-brown-philpot-feat](https://cloud.githubusercontent.com/assets/16053877/13862124/659aa182-ec4e-11e5-9ac5-48bbff110a09.jpg)
![url](https://cloud.githubusercontent.com/assets/16053877/13862125/659ae066-ec4e-11e5-8ca9-48ecd704b191.png)

I will be adding these to the "What Success Looks Like" section at the bottom of the homepage

**Comment by jimmybyrum** [comment]
https://dtlk3t7g5mpz3.cloudfront.net/images/profile-pics/stacey-brown-philpot3.jpg
https://dtlk3t7g5mpz3.cloudfront.net/images/logos/hp-logo.png
