### ISSUE TITLE
[images] upload headshots for community members section on homepage

### ISSUE THREAD

**Issue by lesleykg1** [theBoardlist/website#89]
![joanna-barsh](https://cloud.githubusercontent.com/assets/16053877/13930049/798c8caa-ef5a-11e5-9439-90a956406601.jpg)
![josh-james](https://cloud.githubusercontent.com/assets/16053877/13930098/a7a0e8f2-ef5a-11e5-822d-808ad5c4296f.jpg)
![padmasree-warrior](https://cloud.githubusercontent.com/assets/16053877/13930097/a7a08290-ef5a-11e5-915a-0071eeca33ca.jpg)
![phin-barnes](https://cloud.githubusercontent.com/assets/16053877/13930096/a79f600e-ef5a-11e5-8ce3-24e493186738.jpg)

![sonya-brown](https://cloud.githubusercontent.com/assets/16053877/13930053/79bbbe30-ef5a-11e5-9d8c-ff098670c11f.jpg)
![spencer-rascoff](https://cloud.githubusercontent.com/assets/16053877/13930054/79bc5a0c-ef5a-11e5-9467-b72cf1aa956c.jpg)

**Comment by jimmybyrum** [comment]
I can do these again with file names that match the person if you tell me who they are. :)

https://dtlk3t7g5mpz3.cloudfront.net/images/profile-pics/community-member1.jpg
https://dtlk3t7g5mpz3.cloudfront.net/images/profile-pics/community-member2.jpg
https://dtlk3t7g5mpz3.cloudfront.net/images/profile-pics/community-member3.jpg
https://dtlk3t7g5mpz3.cloudfront.net/images/profile-pics/community-member4.jpg
https://dtlk3t7g5mpz3.cloudfront.net/images/profile-pics/community-member5.jpg
https://dtlk3t7g5mpz3.cloudfront.net/images/profile-pics/community-member6.jpg

**Comment by lesleykg1** [comment]
So weird — looks like some of the images are showing up kind of warped (not perfect circles like Padmasree Warrior's):

![screen shot 2016-03-22 at 10 46 11 am](https://cloud.githubusercontent.com/assets/16053877/13961822/77493cba-f01b-11e5-81da-b82c4a2d668c.png)

This is how I have the HTML:
<div class="layer boardlist-community">
  <h2 ng-hide="{{ true }}">theBoardlist community spans the tech industry</h2>
  <div class="container">
    <ul class="list-unstyled">
      <li>
        <img src="//dtlk3t7g5mpz3.cloudfront.net/images/profile-pics/community-member1.jpg" alt="Joanna Barsh">
        <strong>Joanna Barsh</strong>
        <em>Director Emerita, McKinsey</em>
      </li>
      <li>
        <img src="//dtlk3t7g5mpz3.cloudfront.net/images/profile-pics/community-member2.jpg" alt="Josh James">
        <strong>Josh James</strong>
        <em>Founder/CEO, Domo</em>
      </li>
      <li>
        <img src="//dtlk3t7g5mpz3.cloudfront.net/images/profile-pics/community-member3.jpg" alt="Padmasree Warrior">
        <strong>Padmasree Warrior</strong>
        <em>CEO, NEXTEV</em>
      </li>
      <li>
        <img src="//dtlk3t7g5mpz3.cloudfront.net/images/profile-pics/community-member4.jpg" alt="Phin Barnes">
        <strong>Phin Barnes</strong>
        <em>Parter, First Round Capital</em>
      </li>
      <li>
        <img src="//dtlk3t7g5mpz3.cloudfront.net/images/profile-pics/community-member5.jpg" alt="Sonya Brown">
        <strong>Sonya Brown</strong>
        <em>Partner, Norwest Venture Partners</em>
      </li>
      <li>
        <img src="//dtlk3t7g5mpz3.cloudfront.net/images/profile-pics/community-member6.jpg" alt="Spencer Rascoff">
        <strong>Spencer Rascoff</strong>
        <em>CEO, Zillow Group</em>
      </li>
    </ul>
  </div>
</div>
